[tool.poetry]
name = "fresh-locution"
version = "0.1.0"
description = "Extract fresh locutions from horodated feeds"
authors = ["Mathieu Lecarme <mathieu@garambrogne.net>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
arrow = "^1.3.0"
zstandard = "^0.22.0"
stanza = "^1.6.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.6"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
